export const SET_LOGIN = 'SET_LOGIN'

export const SET_USER = 'SET_USER'
export const SET_CUSTOM = 'SET_CUSTOM'

export const SET_CONVERSATION_LIST = 'SET_CONVERSATION_LIST'

export const SET_CONVERSATION_USER_LIST = 'SET_CONVERSATION_USER_LIST'

export const SET_IM = 'SET_IM'

export const SET_CONNECT_TYPE = 'SET_CONNECT_TYPE'

export const SET_CALL = 'SET_CALL'

export const SET_TELEPHONE = 'SET_TELEPHONE'

export const SET_APPOINTMENTNUM = 'SET_APPOINTMENTNUM'

export const SET_HOME_UNFINISHWORK = 'SET_HOME_UNFINISHWORK'
